In [2]:
import pandas as pd

In [6]:
pd.read_csv('.//iamend_ci//muestras.csv')

     nombre    espesor  conductividad     tt
0   347_M01   2.295833     1051184.21  200.0
1   347_M02   2.340000     1118491.27  300.0
2   347_M03   2.270900     1142610.84  400.0
3   347_M04   2.340000     1216575.14  500.0
4   347_M05   2.329167     1308978.66  600.0
5   347_M06   2.215000     1371864.40  700.0
6   347_M07   2.310000     1387902.82    NaN
7   347_M08   2.302500     1415286.59  800.0
8   347_M09   2.225833     1377247.16    NaN
9   347_M11   2.243000     1432375.75    NaN
10  316_M01   2.302200     1201980.00  200.0
11  316_M02   2.323000     1228240.00  300.0
12  316_M03   2.360000     1263840.00  400.0
13  316_M04   2.342800     1276660.00  500.0
14  316_M05   2.286000     1279890.00  600.0
15  316_M06   2.333000     1328030.00  700.0
16  316_M07   2.313600     1356150.00  800.0
17  316_M08   2.281200     1340660.00  860.0
18  316_M09   2.326800     1307190.00  900.0
19  304_M02   2.289000     1030000.00    NaN
20  304_M03   2.300000     1040000.00    NaN
21  304_M04   2.312000     1060000.00    NaN
22  304_M05   2.317000     1140000.00    NaN
23  304_M06   2.280000     1240000.00    NaN
24  304_M07   2.288000     1260000.00    NaN
25  304_M09   2.268000     1310000.00    NaN
26  304_M11   2.317000     1400000.00    NaN
27     P066  14.957000      610200.00    NaN
28     P068  14.957000     8632000.00    NaN
29     P057  14.957000     3948000.00    NaN
30     P125  14.957000    58910000.00    NaN
31     P064  14.957000    34430000.00    NaN
32     P071  14.957000    17470000.00    NaN